### ISSUE TITLE
Uses cases

### ISSUE THREAD

**Issue by VeriHeppi** [ProjectCED/CED-LLM#10]
Ideas of potential use caes for the application

**Comment by VeriHeppi** [comment]
6 different use cases for the application.

**Comment by janivanhala** [comment]
(Bias to database point of view)

User:
1. Imports a file that contains classifications. (manual, import, ask LLM with training data)
2. Imports use-data in some text form.
3. Sends classification data and use-data to LLM.
4. Waits? (until program receives the LLM answer that is imported to database).
5. From a list, chooses "cat" and "dog" classifications to further analyze the received data. Also choosing to exclude "Car".
6. Sees on screen all the data slices from use-data (which LLM did) that has relationship to "cat" and "dog" but excluding results that has relationship to "Car".
7. Saves the analyzed result.
8. Exports a pdf from the analyzed result.

**Comment by Lauri-Niemela** [comment]
[CED-LLM_Use_cases_v1.0.pdf](https://github.com/user-attachments/files/17200937/CED-LLM_Use_cases_v1.0.pdf)

**Comment by VeriHeppi** [comment]
Fine tuning (add a use case where the user inputs files)

**Comment by Lauri-Niemela** [comment]
[CED-LLM_Use_cases_v2.0.pdf](https://github.com/user-attachments/files/17275018/CED-LLM_Use_cases_v2.0.pdf)
