### ISSUE TITLE
Project Poster

### ISSUE THREAD

**Issue by VeriHeppi** [ProjectCED/CED-LLM#136]

**Comment by janivanhala** [comment]
https://coursepages2.tuni.fi/comp-se-610/guidelines/

### Project poster

See the Moodle submission deadline from the [schedule](https://coursepages2.tuni.fi/comp-se-610/schedule/).

The project poster is an A4-size pdf-document. The poster must contain at least the following information: name of the project in the top of the poster, course details “COMP.SE.610 and 620, autumn 2024”, include at least one screenshot of your application, description of the project and team member names. The posters are not published in electronic form outside the course (only in course’s Moodle forum), but they can be used for educational purposes (for example, to show students what kind of projects have been in done in previous courses).

It is still recommended that the teams publish their posters in github etc. (see, for example [Tomorrow-project](https://github.com/YizhouCodes/Tomorrow/), Poster.png). Check also from the Moodle (under Lecture slides / Sample project posters from previous courses) some example posters from previous courses.

If a team member does not want to publish his/her name in the poster, then you can leave that information out.
