### ISSUE TITLE
Documentation: Frontend

### ISSUE THREAD

**Issue by janivanhala** [ProjectCED/CED-LLM#142]
Manually?

**Comment by VeriHeppi** [comment]
Research best practice for this

**Comment by ilona-timonen** [comment]
JSDoc documentation has been created for the frontend codebase. This documentation includes detailed descriptions of functions, parameters, return values, and other relevant code components.

**Comment by ilona-timonen** [comment]
Frontend documentation: [docs.zip](https://github.com/user-attachments/files/18010837/docs.zip)
