### ISSUE TITLE
Aalto University LLM model research

### ISSUE THREAD

**Issue by vnuotio** [ProjectCED/CED-LLM#15]
Look more into Aalto University's model and its usability.

Some useful links:
- https://huggingface.co/collections/GetmanY1/colloquial-finnish-wav2vec2-665f0d692c7800b0d999920d
- https://huggingface.co/GetmanY1/wav2vec2-base-fi-lp-cont-pt-1500h
- https://huggingface.co/GetmanY1/wav2vec2-large-fi-lp-cont-pt-1500h
- https://github.com/aalto-speech/colloquial-Finnish-wav2vec2?tab=readme-ov-file#pre-trained-and-fine-tuned-models

**Comment by lla1nez** [comment]
The model is limited to the Finnish language, making it less useful for the project as it may expand to other languages (such as English) in the future. Additionally, there is a limited amount of information available about the model, and it is relatively new. Therefore, we will stick with more well-known and supported models within the project.
