### ISSUE TITLE
Test neo4j locally

### ISSUE THREAD

**Issue by VeriHeppi** [ProjectCED/CED-LLM#17]
Test Neo4J locally and get experience from the setup process

**Comment by janivanhala** [comment]
3 ways: just the "raw" database, Neo4j Desktop app and Docker image. https://neo4j.com/deployment-center/

Neo4j Community (raw database):
- Includes web-application of Neo4j Browser that you use through browser
- Bloom requires enterprise version to work outside of Desktop app database.

Neo4j Desktop app:
- Requires a phone number
- Put "Tampere University" as company
- They give activation code (optional). Registration identifies you for commercial agreements and support. I skipped this.
- Manages databases (create/delete/connect/etc)
- This is a platform for all of the Neo4j tools like Browser to manage database and Bloom to visualize it with some management options. Some tools seem to require Java/Node.js environment, but maybe we won't need them.

Docker:
- https://www.docker.com/
- Docker desktop install with recommended settings
- Containers: Neo4j official image
- Bloom requires enterprise version to work outside of Desktop app database.
- Neo4j Browser works fine
- Extra: Extension for Neo4j Browser (no need for Neo4j Desktop app)
- To lock in specific version, best to use Dockerfile
- Neo4j docker image info: https://hub.docker.com/_/neo4j/

With Neo4j Browser you can view/edit the database, this works with any setup. Plugins seem to work on any setup, although installing them is different.

Perhaps start with Neo4j Desktop app to be able to use all possible tools like Bloom. Did not check other tools if they work with Docker. Although Neo4j Browser also can show visualization, but you have to use cypher queries with Bloom you don't need cypher queries.

Other environments:
- Python neo4j driver:
 - requires python >= 3.7
 - https://neo4j.com/docs/python-manual/current/

Other notes:
- Neo4j database default credentials: neo4j / password

**Comment by janivanhala** [comment]
Best to create new DB user with admin rights:
- Launch Neo4j Browser
- Fist item on left side panel -> Connected as -> server user add
- Dont forget to give admin role

**Comment by janivanhala** [comment]
There is a conflict between our project and Neo4j port usage (port 5000).

One way to solve:
- Launch flask first (flask run) before DB is up.
- Start up database from Neo4j Desktop which should popup the problem and pressing the "fix configuration" moves DB discovery to port 5001

**Comment by janivanhala** [comment]
Neo4j supported data types https://neo4j.com/docs/java-manual/current/data-types/
