### ISSUE TITLE
Basic database functions

### ISSUE THREAD

**Issue by vnuotio** [ProjectCED/CED-LLM#32]
- Adding stuff to local db
- Querying stuff from local db
- Basic model/prototype for data/processed results
- (Data class relations?)

**Comment by janivanhala** [comment]
Problems authenticating with default credentials (neo4j/password)

Solved this with adding a new user through Neo4j Browser "server user add" with admin rights.

**Comment by janivanhala** [comment]
Added functions:
- helper functions which in the end do the database query
- Specific functions for:
  - Settings
  - Subject area
  - Result
  - Model
  - Dataset
  - Connections between:
    - Dataset -> Model
    - Dataset -> Subject area

**Comment by janivanhala** [comment]
Database design v1

![Image](https://github.com/user-attachments/assets/b06e44a2-6894-452b-b3d6-c62af77fc7ef)

**Comment by janivanhala** [comment]
With notes
[Database design v2.pdf](https://github.com/user-attachments/files/17257276/Database.design.v2.pdf)

**Comment by janivanhala** [comment]
Result should know which datasets were used. Database design v2.1

[Database design v2.1.pdf](https://github.com/user-attachments/files/17265621/Database.design.v2.1.pdf)

**Comment by janivanhala** [comment]
Might as well use UsedDataset for UsedAnalyzeModel too. Database design v2.2

[Database design v2.2.pdf](https://github.com/user-attachments/files/17265666/Database.design.v2.2.pdf)

**Comment by janivanhala** [comment]
Separated the LLM created structure so it will be much easier to delete.

[Database design v3.pdf](https://github.com/user-attachments/files/17306694/Database.design.v3.pdf)
