### ISSUE TITLE
UI Wireframes V2

### ISSUE THREAD

**Issue by VeriHeppi** [ProjectCED/CED-LLM#37]

**Comment by VeriHeppi** [comment]
Figma? 

Wireframes / Skecthes of all needed pages

**Comment by ilona-timonen** [comment]
[UI Wireframes V2.pdf](https://github.com/user-attachments/files/17209442/UI.Wireframes.V2.pdf)

**Comment by ilona-timonen** [comment]
![Image](https://github.com/user-attachments/assets/786d41de-f016-45ec-964d-6f48504a2da4)
