### ISSUE TITLE
Setup personal Devenv

### ISSUE THREAD

**Issue by VeriHeppi** [ProjectCED/CED-LLM#38]

**Comment by janivanhala** [comment]
My progress:

Git:
- [x] Github ssh key
- [x] git clone
- [ ] branch

Visual Studio Code:
- [x] Extensions: `Python` and `Cypher Query Language`

Neo4j with official app or/and Docker:
- [x] Already installed. #17 

"Conda":
- [x] Installed Anaconda and followed projects readme.md

Node.js for frontend:
- [ ] Installed

Running:
- [x] Tested with flask run (success)
- [ ] Tested with Frontend
- [ ] Tested with Docker-compose
