### ISSUE TITLE
Resrarching Front-end technologies

### ISSUE THREAD

**Issue by VeriHeppi** [ProjectCED/CED-LLM#5]
Which front-end technologies suit this project?
Research for example:
React.js
Vue.js
Something else? 

Brief analysis and decision on which library/framework to use.

**Comment by vnuotio** [comment]
Keep in mind the ease of exporting to other platforms (mobile)

**Comment by ilona-timonen** [comment]
[Front-end technologies.pdf](https://github.com/user-attachments/files/17044148/Front-end.technologies.pdf)
