### ISSUE TITLE
Database: change functions to return true/false instead of string

### ISSUE THREAD

**Issue by janivanhala** [ProjectCED/CED-LLM#51]
Probably most will only return true/false.

If information is returned, make it a tuple?
Examples:
- (True, 'data')
- (False, None)

**Comment by vnuotio** [comment]
When returning data, data should be returned if successful, None if failed

**Comment by janivanhala** [comment]
Database seems to be happy when not finding anything on modification/deletion/connection so it returns True. Have to check these before hand to get any other False returns than database connection errors.

**Comment by janivanhala** [comment]
Returns:
- True when query succeeded
- False when something went wrong
- <data> when getting property data
- None when there isn't any data to be found
