### ISSUE TITLE
Database: Basic Data Saving

### ISSUE THREAD

**Issue by VeriHeppi** [ProjectCED/CED-LLM#58]
Database needs to save a project - results, used blueprint and title of the text data file should be saved under a project

A single project can have multiple analyses under it, so it functions sort of like a folder (analysis = text data filename + results + used blueprint)

**Comment by janivanhala** [comment]
depends on #62

**Comment by janivanhala** [comment]
Example

`  

    # add project and give it a name:
    project_id = db.add_project_node()
    db.set_project_property(project_id, NodeProperties.Project.NAME, 'projekti')

    # add blueprints + name
    blueprint_id = db.add_blueprint_node()
    db.set_blueprint_property(blueprint_id, NodeProperties.Blueprint.NAME, 'blueprint 1')
    blueprint_id_2 = db.add_blueprint_node()
    db.set_blueprint_property(blueprint_id_2, NodeProperties.Blueprint.NAME, 'blueprint 2')
    blueprints = [blueprint_id, blueprint_id_2]

    # add data models + name
    datamodel_id = db.add_data_model_node()
    db.set_data_model_property(datamodel_id, NodeProperties.DataModel.NAME, 'd-model 1')
    datamodel_id_2 = db.add_data_model_node()
    db.set_data_model_property(datamodel_id_2, NodeProperties.DataModel.NAME, 'd-model 2')
    datamodels = [datamodel_id, datamodel_id_2]

    # collect dataset file_names
    data_sets = ['datasetti 1', 'datasetti 2', 'datasetti 3']

    # <press analyse>

    # make result_blueprint node and add LLM result to it
    result_id = db.add_result_blueprint_node(project_id, data_sets, blueprints, datamodels)
    db.set_result_blueprint_property(result_id, NodeProperties.ResultBlueprint.RESULT, 'LLM text response here')


    # lookup LLM result
    print(db.lookup_result_blueprint_property(result_id, NodeProperties.ResultBlueprint.RESULT))
    # console: LLM text response here

    # get list of projects [id, name]
    print(db.lookup_project_nodes())
    # console: ['d0a5a7d4-b4c0-451a-bdee-f64fcde91c24', 'projekti']

    # get list of results to certain project [id, datetime]
    print(db.lookup_result_blueprint_nodes(project_id))
    # console: ['cc476462-8b83-48b7-9071-1da3e9808e99', '2024-10-15T21:46:19.953991']
`
