### ISSUE TITLE
Setup Backend API

### ISSUE THREAD

**Issue by VeriHeppi** [ProjectCED/CED-LLM#59]
Calling backend API functions from the frontend

Done in the routes.py file

**Comment by vnuotio** [comment]
Very simple example: https://www.tutorialspoint.com/python_network_programming/python_routing.htm

**Comment by VeriHeppi** [comment]
Some useful sources and examples of REST api cretion with python:

https://www.youtube.com/watch?v=z3YMz-Gocmw
https://www.integrate.io/blog/an-introduction-to-rest-api-with-python/
https://realpython.com/api-integration-in-python/
