### ISSUE TITLE
Researching Database technologies

### ISSUE THREAD

**Issue by VeriHeppi** [ProjectCED/CED-LLM#8]
Comparison of possible database technologies. How close to standard SQL should it be?

Neo4j?
MySQL Vector Extension?

**Comment by vnuotio** [comment]
Research 'swappability' of different technologies: How similar are the instructions/language, can solutions be swapped for another without major reworks to the code?

**Comment by vnuotio** [comment]
Database/env. can be containerized from the start.

**Comment by janivanhala** [comment]
[database research.pdf](https://github.com/user-attachments/files/17048519/database.research.pdf)

Result:
Neo4j seems to have a good chance for providing all the utilities from start to end from prototyping point of view. While MySQL vector extension might not have needed features after midway of the project.
