### ISSUE TITLE
Create table that explains terms

### ISSUE THREAD

**Issue by VeriHeppi** [ProjectCED/CED-LLM#93]

**Comment by janivanhala** [comment]
Analysis steps: 
- Initial analysis: 
  - Analysis with whole dataset using LLM
- Further analysis:
  - Analysis using local DB first
  - Optionally LLM to summarize the DB result which would lead to similar result as on the first analysis

"Classifications":
- Blueprint:
  - Analysis by questions
  - Used in initial analysis and perhaps also in further analysis
- Data-model:
  - Important-to-know things about the subject area.
  - Given to LLM with the use-dataset to construct the local DB for further analysis
- Analyse-model (work in progress):
  - "keywords"
  - Used for DB search in further analysis

**Comment by janivanhala** [comment]
Removed from this project:
- Further analysis
- Data-model
- Analyse-model (WIP)

**Comment by VeriHeppi** [comment]
Official term list:
- Blueprint: A set of rules and keywords used to help LLM classify the data file
- Classification: Process. The general process where the user inputs a file and uses Blueprint to classify data
- Result/Analysis result:
