### ISSUE TITLE
Use cases for further analysis

### ISSUE THREAD

**Issue by vnuotio** [ProjectCED/CED-LLM#95]
Simple use cases explaining the use of DataModels.

**Comment by janivanhala** [comment]
Adding on to these [CED-LLM_Use_cases_v2.0.pdf](https://github.com/user-attachments/files/17275018/CED-LLM_Use_cases_v2.0.pdf):

Data model would be a part of "classification" where user would list possible things (labels) and list relationships (relationships) between them. Kind of like important-to-know about this subject area. This will give LLM the knowledge to pick relevant information and how the relate to each other for user to know about.

### Use case Milla (journalist transcribes):
- Labels:
  - Participant
  - Topic
  - Contribution (text/data segment)
  - Engagement metric (word count / speaking frequency)
- Relationships:
  - MADE (participant -> data sample)
  - RELATES_TO (data sample -> topic)
  - INVOLVES (participant -> topic)
  - INDICATES (engagement metric -> participant / contribution)

Milla opens up the program and creates a data model of interesting parts with above information. She saves the data model for later use.

_(after first analysis)_

Milla notices interesting points but with very little information about those points. She adjusts "classification" slightly and presses analyse again. Program re-analyses the data quicker as only the database search result is sent to LLM. Second result provides her with more accurate result on the specific point.

### Use case Timo (security logs):
Data model:
- Labels:
  - User
  - IP Address
  - Event
  - Threat Indicator (failed logins, location deviations,..)
  - Classification (normal, suspicious, unusual)
- Relationships:
  - ORIGINATES_FROM (event -> IP)
  - PERFORMED_BY (event -> user)
  - FLAGGED_AS (IP/event -> threat indicator)
  - HAS_CLASSIFICATION (event -> classification)
  - ASSOCIATED_WITH (threat indicator -> event)

Timo opens up the program and creates a data model and saves it. Over time he update his data model to be as above.

_(after first analysis)_

After the first analysis, Timo notices some possible suspicious activity from certain IP address but is not sure on the thread level. Timo chooses another "classification" and quickly re-analyses the filled-data-structure multiple times locally, adjusting "classification" in between analyses. When satisfied on "classification", he opts in to have LLM to summarise the database result so he can quickly show the result to his not-so-security-knowledged superior.


### Use case Kalle (dog show):
Data model:
- Labels:
  - Dog show
  - Judge
  - Breed
  - Outcome
  - Factor (key success factors like judge preferences, location, competition size)
- Relationships:
  - HOSTED (dog show -> factor location)
  - EVALUATED_BY (outcome -> judge)
  - ASSOCIATED_WITH (judge -> factor preferences/scoring)
  - INCLUDES (dog show -> breeds)
  - INFLUENCES (factor -> breed / outcome)

Kalle opens up the program and asks LLM with some training dataset for good data model. He quickly goes through the result removing unimportant things from it. He ends up with above setup. He saves the data model.

_(after first analysis)_

After getting information about which dog shows to go to. Kalle makes quick re-analyses of how well would his known-current-rivals would fare on those dog shows from the initial result. In the end, Kalle now has better understanding which of the first result dog shows he would have most advantage.

### Use case Hannu (human resources):
Data model:
- Labels:
  - Employee
  - Department
  - Performance Metric
  - Classification (high, moderate, under performer)
  - Turnover Rate
- Relationships:
  - BELONGS_TO (employee -> department)
  - EVALUATED_BY (employee -> performance metric)
  - ASSIGNED_AS (employee -> Classification label)
  - CONTRIBUTES_TO (performance metric -> department performance/outcomes)
  - INDICATES (high turnover rate -> department)

Hannu opens up the program and chooses pre-made data model for his case. This is shown above.

_(new first analysis)_

LLM analyses performance reports and gives a high-level-summary of the current state of the human resources. Then he quickly re-analyses the interesting edge-cases (under performer/high performer) further. He now also has more detailed information to make better cases for change in the company.

**Comment by janivanhala** [comment]
# CED-LLM Use cases v3.0

[use case v3.pdf](https://github.com/user-attachments/files/17649250/use.case.v3.pdf)



Presenting use cases for data-model usage and further analysis. Using v2.0 use cases as basis.

Data-model would be a list things (labels) and list relationships (relationships) between them, like important-to-know things about this subject area. This will give LLM the knowledge to pick or/and connect relevant information and how they relate to each other to create the filled-data-structure that is imported to local database for further analysis.

Further analysis is started by using local database and giving the result to user as “raw” or send to LLM to summarise with a possibility of having blueprint-like questions being present in this analysis step as well. This would make result appear more faster and cost of using LLM lower as only the data from DB search result would be sent to LLM, not the whole dataset. Caveat would be that user would need to wait for the LLM-filled-data-structure to be made.

_Text in italic and blueish is mentioned in v2.0 for reminder._
